//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GXDLMSDirector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GXDLMSDirector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gurux GXDLMSDirector.
        /// </summary>
        internal static string AboutGXDLMSDirectorTxt {
            get {
                return ResourceManager.GetString("AboutGXDLMSDirectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectMnu {
            get {
                object obj = ResourceManager.GetObject("ConnectMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright© 1998-2017 Gurux Ltd.
        ///All rights reserved..
        /// </summary>
        internal static string CopyrightTxt {
            get {
                return ResourceManager.GetString("CopyrightTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteMnu {
            get {
                object obj = ResourceManager.GetObject("DeleteMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux GXDLMSDirector files (*.gxc)|*.gxc|All files (*.*)|*.*.
        /// </summary>
        internal static string FilterTxt {
            get {
                return ResourceManager.GetString("FilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For information about Gurux products see:.
        /// </summary>
        internal static string ForMoreInfoTxt {
            get {
                return ResourceManager.GetString("ForMoreInfoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux GXDLMSDirector.
        /// </summary>
        internal static string GXDLMSDirectorTxt {
            get {
                return ResourceManager.GetString("GXDLMSDirectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a hardware fault..
        /// </summary>
        internal static string HardwareFaultTxt {
            get {
                return ResourceManager.GetString("HardwareFaultTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a inconsistent Class or Object..
        /// </summary>
        internal static string InconsistentClassTxt {
            get {
                return ResourceManager.GetString("InconsistentClassTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manufacturer settings are not present. Do you want to install them online from Gurux Web?.
        /// </summary>
        internal static string InstallManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("InstallManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewMnu {
            get {
                object obj = ResourceManager.GetObject("NewMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenMnu {
            get {
                object obj = ResourceManager.GetObject("OpenMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsMnu {
            get {
                object obj = ResourceManager.GetObject("OptionsMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications updated..
        /// </summary>
        internal static string ProtocolsUpdatedTxt {
            get {
                return ResourceManager.GetString("ProtocolsUpdatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadMnu {
            get {
                object obj = ResourceManager.GetObject("ReadMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports Read-Write denied..
        /// </summary>
        internal static string ReadWriteDeniedTxt {
            get {
                return ResourceManager.GetString("ReadWriteDeniedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected device(s)?.
        /// </summary>
        internal static string RemoveDeviceConfirmation {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected object?.
        /// </summary>
        internal static string RemoveObjectConfirmation {
            get {
                return ResourceManager.GetString("RemoveObjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must be restarted to apply the changes..
        /// </summary>
        internal static string RestartTxt {
            get {
                return ResourceManager.GetString("RestartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string SaveChangesTxt {
            get {
                return ResourceManager.GetString("SaveChangesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveMnu {
            get {
                object obj = ResourceManager.GetObject("SaveMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a temporary failure..
        /// </summary>
        internal static string TemporaryFailureTxt {
            get {
                return ResourceManager.GetString("TemporaryFailureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unavailable object..
        /// </summary>
        internal static string UnavailableObjectTxt {
            get {
                return ResourceManager.GetString("UnavailableObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a undefined object..
        /// </summary>
        internal static string UndefinedObjectTxt {
            get {
                return ResourceManager.GetString("UndefinedObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string UnknownErrorTxt {
            get {
                return ResourceManager.GetString("UnknownErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unmatched type..
        /// </summary>
        internal static string UnmatchedTypeTxt {
            get {
                return ResourceManager.GetString("UnmatchedTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Manufacturer settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdateManufacturersOnline2Txt {
            get {
                return ResourceManager.GetString("UpdateManufacturersOnline2Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Manufacturer settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdateManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("UpdateManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value changed.
        /// </summary>
        internal static string ValueChangedTxt {
            get {
                return ResourceManager.GetString("ValueChangedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WriteMnu {
            get {
                object obj = ResourceManager.GetObject("WriteMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
