//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GXDLMSDirector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GXDLMSDirector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gurux GXDLMSDirector.
        /// </summary>
        internal static string AboutGXDLMSDirectorTxt {
            get {
                return ResourceManager.GetString("AboutGXDLMSDirectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Implemented..
        /// </summary>
        internal static string ActionImplemented {
            get {
                return ResourceManager.GetString("ActionImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Cipher Key.
        /// </summary>
        internal static string BlockCipherKeyTxt {
            get {
                return ResourceManager.GetString("BlockCipherKeyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cct {
            get {
                object obj = ResourceManager.GetObject("cct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cct1 {
            get {
                object obj = ResourceManager.GetObject("cct1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected Conformance Test results?.
        /// </summary>
        internal static string ConformanceTestRemove {
            get {
                return ResourceManager.GetString("ConformanceTestRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectMnu {
            get {
                object obj = ResourceManager.GetObject("ConnectMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright© 1998-2020 Gurux Ltd.
        ///All rights reserved..
        /// </summary>
        internal static string CopyrightTxt {
            get {
                return ResourceManager.GetString("CopyrightTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to perform conformational tests. This may take a very long time or harm your meter. Do you want to continue?.
        /// </summary>
        internal static string CTTWarning {
            get {
                return ResourceManager.GetString("CTTWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteMnu {
            get {
                object obj = ResourceManager.GetObject("DeleteMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.dll)|*.dll|All files (*.*)|*.*.
        /// </summary>
        internal static string ExecutableFilesTxt {
            get {
                return ResourceManager.GetString("ExecutableFilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available..
        /// </summary>
        internal static string ExternalMediaNoUpdates {
            get {
                return ResourceManager.GetString("ExternalMediaNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected external media?.
        /// </summary>
        internal static string ExternalMediaRemove {
            get {
                return ResourceManager.GetString("ExternalMediaRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux GXDLMSDirector files (*.gxc)|*.gxc|All files (*.*)|*.*.
        /// </summary>
        internal static string FilterTxt {
            get {
                return ResourceManager.GetString("FilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For information about Gurux products see:.
        /// </summary>
        internal static string ForMoreInfoTxt {
            get {
                return ResourceManager.GetString("ForMoreInfoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux GXDLMSDirector.
        /// </summary>
        internal static string GXDLMSDirectorTxt {
            get {
                return ResourceManager.GetString("GXDLMSDirectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Help topic is associated with this item..
        /// </summary>
        internal static string HelpNotAvailable {
            get {
                return ResourceManager.GetString("HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manufacturer settings are not present. Do you want to install them online from Gurux Web?.
        /// </summary>
        internal static string InstallManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("InstallManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ASCII characters..
        /// </summary>
        internal static string InvalidASCII {
            get {
                return ResourceManager.GetString("InvalidASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutations are not available..
        /// </summary>
        internal static string InvalidDurationFile {
            get {
                return ResourceManager.GetString("InvalidDurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values are not available..
        /// </summary>
        internal static string InvalidValueFile {
            get {
                return ResourceManager.GetString("InvalidValueFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Manufacturer Settings first..
        /// </summary>
        internal static string ManufacturerSettingsMissing {
            get {
                return ResourceManager.GetString("ManufacturerSettingsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewMnu {
            get {
                object obj = ResourceManager.GetObject("NewMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifyMnu {
            get {
                object obj = ResourceManager.GetObject("NotifyMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are open connections. Do you want to close them first?.
        /// </summary>
        internal static string OpenConnectionsTxt {
            get {
                return ResourceManager.GetString("OpenConnectionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenMnu {
            get {
                object obj = ResourceManager.GetObject("OpenMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsMnu {
            get {
                object obj = ResourceManager.GetObject("OptionsMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications updated..
        /// </summary>
        internal static string ProtocolsUpdatedTxt {
            get {
                return ResourceManager.GetString("ProtocolsUpdatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to read Association view to see all objects what the meter can offer. Do you want to do it now?.
        /// </summary>
        internal static string ReadAssociationView {
            get {
                return ResourceManager.GetString("ReadAssociationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadMnu {
            get {
                object obj = ResourceManager.GetObject("ReadMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyTxt {
            get {
                return ResourceManager.GetString("ReadyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected device(s)?.
        /// </summary>
        internal static string RemoveDeviceConfirmation {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected object?.
        /// </summary>
        internal static string RemoveObjectConfirmation {
            get {
                return ResourceManager.GetString("RemoveObjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must be restarted to apply the changes..
        /// </summary>
        internal static string RestartTxt {
            get {
                return ResourceManager.GetString("RestartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string SaveChangesTxt {
            get {
                return ResourceManager.GetString("SaveChangesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveMnu {
            get {
                object obj = ResourceManager.GetObject("SaveMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System title.
        /// </summary>
        internal static string SystemTitleTxt {
            get {
                return ResourceManager.GetString("SystemTitleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Manufacturer settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdateManufacturersOnline2Txt {
            get {
                return ResourceManager.GetString("UpdateManufacturersOnline2Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Manufacturer settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdateManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("UpdateManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value changed.
        /// </summary>
        internal static string ValueChangedTxt {
            get {
                return ResourceManager.GetString("ValueChangedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux GXDLMSDirector values (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string ValuesFilterTxt {
            get {
                return ResourceManager.GetString("ValuesFilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WriteMnu {
            get {
                object obj = ResourceManager.GetObject("WriteMnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
